globalConfig:
  gatewayAuth:
    gatewayAccessType: access_key
    gatewayCredentialsExistingSecret: akeyless-auth

gateway:
  service:
    type: ClusterIP

sra:
  sshConfig:
    service:
      type: ClusterIP

extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "{{ .Release.Name }}-extra"
      namespace: "{{ .Release.Namespace }}"
    data:
      release: "{{ .Release.Name }}"
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: "{{ .Release.Name }}-extra"
      namespace: "{{ .Release.Namespace }}"
    spec:
      podSelector:
        matchLabels:
          extra-objects/selects: nothing
      policyTypes:
        - Ingress
  - |
    apiVersion: v1
    kind: Service
    metadata:
      name: "{{ .Release.Name }}-extra"
      namespace: "{{ .Release.Namespace }}"
    spec:
      type: ClusterIP
      ports:
        - name: probe
          port: {{ add 8000 (len .Release.Name) }}
          targetPort: 8080
