globalConfig:
  gatewayAuth:
    gatewayAccessType: access_key
    gatewayCredentialsExistingSecret: akeyless-auth

gateway:
  deployment:
    extraVolumes:
      - name: akeyless-run
        emptyDir: {}
    extraVolumeMounts:
      - name: akeyless-run
        mountPath: /run/akeyless
  service:
    type: ClusterIP

sra:
  sshConfig:
    service:
      type: ClusterIP
