globalConfig:
  gatewayAuth:
    gatewayAccessType: access_key
    gatewayCredentialsExistingSecret: akeyless-auth

gateway:
  service:
    type: ClusterIP

sra:
  sshConfig:
    service:
      type: ClusterIP
