globalConfig:
  gatewayAuth:
    gatewayAccessType: access_key
    gatewayCredentialsExistingSecret: akeyless-auth

gateway:
  deployment:
    extraVolumes:
      - name: akeyless-run
        emptyDir: {}
    extraVolumeMounts:
      - name: akeyless-run
        mountPath: /run/akeyless
  service:
    type: ClusterIP

cacheHA:
  enabled: true
  replicas: 3
  auth: true
  hardAntiAffinity: false
  persistentVolume:
    enabled: false
  redis:
    port: 6379
    tlsPort: 0
    tlsReplication: false
  sentinel:
    port: 26379
    tlsPort: 0
    tlsReplication: false

sra:
  sshConfig:
    service:
      type: ClusterIP
