globalConfig:
  gatewayAuth:
    gatewayAccessType: access_key
    gatewayCredentialsExistingSecret: akeyless-auth

gateway:
  service:
    type: ClusterIP
  deployment:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: akeyless-gateway

sra:
  sshConfig:
    service:
      type: ClusterIP
