apiVersion: v1
kind: Secret
metadata:
  name: customerfragments
type: Opaque
stringData:
  customer-fragments: |
    {
      "customer_fragments": [
        {
          "id": "cf-chart-testing",
          "value": "dummy-customer-fragment-value",
          "description": "chart testing fixture",
          "name": "chart-testing"
        }
      ]
    }
