apiVersion: v1
kind: Secret
metadata:
  name: gw-metrics-secret
type: Opaque
stringData:
  otel-config.yaml: |
    exporters:
      datadog:
        api:
          key: dummy-datadog-api-key
    service:
      pipelines:
        metrics:
          exporters:
            - datadog
