# Default values for spot-config-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  labels: {}
  # Remove the {} and add any needed values to your SecurityContext
  securityContext: {}
#    fsGroup: 3000
#    runAsUser: 65534

replicaCount: 2
openshiftEnabled: false
debug: false

gatewayCert:
  #  Specifies an existing secret for gateway tls certificate must include:
  # - tls.crt (base64)
  tlsCertsSecretName:

#Remove the {} and add any needed values to your SecurityContext here, do not change runAsUser and allowPrivilegeEscalation
containerSecurityContext: {}
#  seccompProfile:
#    type: RuntimeDefault

image:
  repository: docker.registry-2.akeyless.io/k8s-webhook-server
  agentImage: docker.registry-2.akeyless.io/k8s-secrets-sidecar

##   Alternative mirror registry
#  repository: akeyless/k8s-webhook-server
#  agentImage: akeyless/k8s-secrets-sidecar

  pullPolicy: IfNotPresent

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  # name: ""
  # Optional additional annotations to add to the controller's ServiceAccount
  # annotations: {}
  # Automount API credentials for a Service Account.
  automountServiceAccountToken: true
  labels: {}

service:
  name: secrets-webhook
  type: ClusterIP
  externalPort: 443
  internalPort: 8443
  labels: {}

env:
  AKEYLESS_URL: "https://vault.akeyless.io"
  AKEYLESS_ACCESS_ID: "" 
  AKEYLESS_ACCESS_TYPE: ""  # azure_ad/aws_iam/api_key/k8s

 # AKEYLESS_API_GW_URL: "https://api-gw-url"
 # AKEYLESS_POD_ACCESS_PATH: "<location-to-access-secrets-per-pod-name>"
 # AKEYLESS_NAMESPACE_ACCESS_PATH: "<location-to-access-secrets-per-namespace>"
 # AKEYLESS_SECRET_DIR_NAME: "<path>"
 # AKEYLESS_API_KEY: "<api_key>"
 # AKEYLESS_CRASH_POD_ON_ERROR: "enable"
 # AKEYLESS_K8S_AUTH_CONF_NAME: "K8s_conf_name"
 
 # the gw base64 certificate file e.g: 'cat my-gw.crt | base64'
 # AKEYLESS_GW_CERTIFICATE: 


  AKEYLESS_AGENT_LIMITS_CPU: "500m"
  AKEYLESS_AGENT_REQUESTS_CPU: "250m"
  AKEYLESS_AGENT_LIMITS_MEM: "128Mi"
  AKEYLESS_AGENT_REQUESTS_MEM: "64Mi"
 

resources:
  limits:
    cpu: 0.5
    memory: 192Mi
  requests:
    cpu: 0.25
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: |
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app: {{ template "vault-secrets-webhook.name" . }}
            release: {{ .Release.Name }}

HPA:
  # Note that metrics server must be installed for this to work:
  # https://github.com/kubernetes-sigs/metrics-server
  enabled: false
  minReplicas: 1
  maxReplicas: 14
  cpuAvgUtil: 50
  memAvgUtil: 50

  annotations: {}