# Default values for spot-config-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  labels: { }
  # Remove the {} and add any needed values to your SecurityContext
  securityContext: { }
#    fsGroup: 3000
#    runAsUser: 65534

replicaCount: 1
openshiftEnabled: false
useExistingInjectorCert: true
debug: false

gatewayCert:
  #  Specifies an existing secret for gateway tls certificate must include:
  # - tls.crt (base64)
  tlsCertsSecretName:

#Remove the {} and add any needed values to your SecurityContext here, do not change runAsUser and allowPrivilegeEscalation
containerSecurityContext: { }
#  seccompProfile:
#    type: RuntimeDefault

image:
  #  repository: docker.registry-2.akeyless.io/k8s-webhook-server
  #  agentImage: docker.registry-2.akeyless.io/k8s-secrets-sidecar

  ##   Alternative mirror registry
  repository: akeyless/k8s-webhook-server
  agentImage: akeyless/k8s-secrets-sidecar
  tag: local
  pullPolicy: Never

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  # name: ""
  # Optional additional annotations to add to the controller's ServiceAccount
  # annotations: {}
  # Automount API credentials for a Service Account.
  automountServiceAccountToken: true
  labels: { }

restartRollout:
  enabled: false
  interval: 1m

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30
  failureThreshold: 5

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5

service:
  name: secrets-webhook
  type: ClusterIP
  externalPort: 443
  internalPort: 8443
  labels: { }

# for EKS using custom CNI
#hostNetwork: true

env:
  AKEYLESS_URL: "https://vault.akeyless.io"
  #  AKEYLESS_ACCESS_ID: "p-rfmykxp0rri4wm"
  #  AKEYLESS_ACCESS_TYPE: "aws_iam"  # azure_ad//api_key/k8s

  AKEYLESS_ACCESS_ID: "p-hinp0za46x15am"
  AKEYLESS_ACCESS_TYPE: "api_key"  # azure_ad//api_key/k8s
  AKEYLESS_API_KEY: "IyEspVaUy7Q30BqWd/lDSNto8QLKgORns3e3wKF/+s4="
  AKEYLESS_API_GW_URL: "http://aba9ca748ac5a4ed990621ab330b59f2-2046007610.us-east-2.elb.amazonaws.com:8000/api/v1"
  # AKEYLESS_CRASH_POD_ON_ERROR: "enable"
  # AKEYLESS_K8S_AUTH_CONF_NAME: "K8s_conf_name"

  # the gw base64 certificate file e.g: 'cat my-gw.crt | base64'
  # AKEYLESS_GW_CERTIFICATE:


  AKEYLESS_AGENT_LIMITS_CPU: "500m"
  AKEYLESS_AGENT_REQUESTS_CPU: "250m"
  AKEYLESS_AGENT_LIMITS_MEM: "128Mi"
  AKEYLESS_AGENT_REQUESTS_MEM: "64Mi"


resources:
  limits:
    cpu: 0.5
    memory: 192Mi
  requests:
    cpu: 0.25
    memory: 128Mi

nodeSelector: { }

tolerations: [ ]

affinity: |
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app: {{ template "vault-secrets-webhook.name" . }}
            release: {{ .Release.Name }}

HPA:
  # Note that metrics server must be installed for this to work:
  # https://github.com/kubernetes-sigs/metrics-server
  enabled: false
  minReplicas: 1
  maxReplicas: 14
  cpuAvgUtil: 50
  memAvgUtil: 50

  annotations: { }