apiVersion: v2
name: akeyless-gateway
version: 3.2.0
description: A Helm chart for Kubernetes that deploys akeyless-gateway
home: https://github.com/akeylesslabs/helm-charts/tree/main/charts/akeyless-gateway
maintainers:
  - name: Akeyless
    email: support@akeyless.io
    url: https://www.akeyless.io
type: application
keywords:
  - akeyless-gateway
  - sra
icon: https://akeyless-908832575.imgix.net/wp-content/uploads/2024/03/akeyless-2024.png?auto=format%2Ccompress&fm=webp&ixlib=php-3.3.0
appVersion: 5.0.0_3.1.0
annotations:
  gatewayVersion: 5.0.0
  sraVersion: 3.1.0
dependencies:
  - name: redis-ha
    version: 4.35.10
    repository: https://dandydeveloper.github.io/charts/
    condition: cacheHA.enabled
    alias: cacheHA
