apiVersion: v1
kind: Secret
metadata:
  name: docker-akeyless-staging
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJybmQtYWxsQGFrZXlsZXNzLmlvIiwicGFzc3dvcmQiOiJkY2tyX3BhdF9ldlk5cUxtclJSUVR5YUVJTVpib2VDN2hjTnMiLCJhdXRoIjoiY201a0xXRnNiRUJoYTJWNWJHVnpjeTVwYnpwa1kydHlYM0JoZEY5bGRsazVjVXh0Y2xKU1VWUjVZVVZKVFZwaWIyVkROMmhqVG5NPSJ9fX0=
