{{- if eq .Values.ztpConfig.enabled true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-cm-ztp
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $.Values.ztpConfig.containerName }}
    chart: {{ $.Chart.Name }}
data:
  env-config.js: |
    window._env_ = {
        CLI_GW_DNS: {{ $.Values.apiGatewayURL | quote }},
        AUTH_DNS: 'https://auth.akeyless.io',
        CERT_AUTH_DNS: 'https://auth-cert.akeyless.io',
        CLI_GW_DNS_V_2: 'https://api.akeyless.io'
    };
    {{- end }}