replicaCount: 1

env:
  AKEYLESS_ACCESS_TYPE: api_key
  AKEYLESS_ACCESS_ID: p-12345678911123
  AKEYLESS_API_KEY: ZHVtbXktYXBpLWtleQ==

webhook:
  tls:
    existingSecretName: injector-tls-ci
    caBundleAnnotations:
      cert-manager.io/inject-ca-from: chart-testing/injector-tls-ci
