{{- $cacheHa := index .Values "cacheHA" -}}
{{- if and (eq "true" (include "akeyless-gateway.clusterCache.enabled" . )) (not $cacheHa.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{  include "akeyless-gateway.clusterCache.SvcName" . }}
  labels:
{{- include "akeyless-gateway.labels" . | nindent 4 }}
spec:
  ports:
    - port: 6379
      protocol: TCP
  selector:
    {{- include "akeyless-gateway.clusterCache.labels" . | nindent 4 }}
  type: ClusterIP
{{- end }}