{{- /*
Copyright Akeyless, Inc. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- include "cache-ha.validateStorageClass" . -}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cache-ha.fullname" . }}-cache
  namespace: {{ include "cache-ha.namespace" . }}
  labels: {{- include "cache-ha.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.componentNames.cache | default "cache" }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "cache-ha.commonAnnotations" . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.node.replicaCount }}
  revisionHistoryLimit: {{ .Values.node.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels: {{- include "cache-ha.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.componentNames.cache | default "cache" }}
  serviceName: {{ include "cache-ha.headlessServiceName" . }}
  {{- if .Values.node.updateStrategy }}
  updateStrategy: {{- toYaml .Values.node.updateStrategy | nindent 4 }}
  {{- end }}
  {{- if .Values.node.podManagementPolicy }}
  podManagementPolicy: {{ .Values.node.podManagementPolicy | quote }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "cache-ha.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.componentNames.cache | default "cache" }}
      {{- if .Values.node.podAnnotations }}
      annotations: {{- toYaml .Values.node.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if .Values.commonAnnotations }}
      {{- include "cache-ha.commonAnnotations" . | nindent 8 }}
      {{- end }}
    spec:
      {{- if and .Values.node.podSecurityContext .Values.node.podSecurityContext.enabled }}
      securityContext: {{- toYaml .Values.node.podSecurityContext | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cache-ha.serviceAccountName" . }}
      {{- if .Values.node.affinity }}
      affinity: {{- toYaml .Values.node.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.node.nodeSelector }}
      nodeSelector: {{- toYaml .Values.node.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.node.tolerations }}
      tolerations: {{- toYaml .Values.node.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.node.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml .Values.node.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if .Values.node.priorityClassName }}
      priorityClassName: {{ .Values.node.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.node.schedulerName }}
      schedulerName: {{ .Values.node.schedulerName | quote }}
      {{- end }}
      {{- if .Values.node.dnsPolicy }}
      dnsPolicy: {{ .Values.node.dnsPolicy }}
      {{- end }}
      {{- if .Values.node.dnsConfig }}
      dnsConfig: {{- toYaml .Values.node.dnsConfig | nindent 8 }}
      {{- end }}
      {{- if .Values.node.hostAliases }}
      hostAliases: {{- toYaml .Values.node.hostAliases | nindent 8 }}
      {{- end }}
      {{- if .Values.node.shareProcessNamespace }}
      shareProcessNamespace: {{ .Values.node.shareProcessNamespace }}
      {{- end }}
      {{- if .Values.node.automountServiceAccountToken }}
      automountServiceAccountToken: {{ .Values.node.automountServiceAccountToken }}
      {{- end }}
      {{- if .Values.node.enableServiceLinks }}
      enableServiceLinks: {{ .Values.node.enableServiceLinks }}
      {{- end }}
      {{- if .Values.node.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.node.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        - name: cache
          image: {{ include "cache-ha.node.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if and .Values.node.containerSecurityContext .Values.node.containerSecurityContext.enabled }}
          securityContext: {{- toYaml .Values.node.containerSecurityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.node.lifecycleHooks }}
          lifecycle: {{- toYaml .Values.node.lifecycleHooks | nindent 12 }}
          {{- else }}
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -ec
                  - /scripts/prestop-cache.sh
          {{- end }}
          command:
            - /bin/sh
            - -ec
            - /scripts/start-cache.sh
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CACHE_MASTER_SET
              value: {{ .Values.sentinel.masterSet | quote }}
            - name: CACHE_QUORUM
              value: {{ include "cache-ha.sentinelQuorum" . | quote }}
            - name: CACHE_DOWN_AFTER_MS
              value: {{ .Values.sentinel.downAfterMilliseconds | quote }}
            - name: CACHE_FAILOVER_TIMEOUT
              value: {{ .Values.sentinel.failoverTimeout | quote }}
            - name: CACHE_PARALLEL_SYNCS
              value: {{ .Values.sentinel.parallelSyncs | quote }}
            {{- if .Values.auth.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cache-ha.secretName" . }}
                  key: {{ include "cache-ha.secretPasswordKey" . }}
            {{- end }}
            {{- if .Values.node.extraEnvVars }}
            {{- toYaml .Values.node.extraEnvVars | nindent 12 }}
            {{- end }}
          {{- if or .Values.node.extraEnvVarsCM .Values.node.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.node.extraEnvVarsCM }}
            - configMapRef:
                name: {{ .Values.node.extraEnvVarsCM }}
            {{- end }}
            {{- if .Values.node.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.node.extraEnvVarsSecret }}
            {{- end }}
          {{- end }}
          ports:
            - name: cache
              containerPort: {{ .Values.ports.cache }}
              protocol: TCP
          {{- if .Values.node.livenessProbe.enabled }}
          livenessProbe:
            {{- if .Values.node.livenessProbe.customLivenessProbe }}
            {{- toYaml .Values.node.livenessProbe.customLivenessProbe | nindent 12 }}
            {{- else }}
            {{- if .Values.tls.enabled }}
            exec:
              command:
                - /bin/sh
                - -c
                - redis-cli --tls --cert {{ .Values.paths.tlsDir }}/{{ .Values.paths.tlsCertFile }} --key {{ .Values.paths.tlsDir }}/{{ .Values.paths.tlsKeyFile }} --cacert {{ .Values.paths.tlsDir }}/{{ .Values.paths.tlsCaCertFile }} -p {{ .Values.ports.cache }} ping
            {{- else }}
            tcpSocket:
              port: cache
            {{- end }}
            initialDelaySeconds: {{ .Values.node.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.node.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.node.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.node.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.node.livenessProbe.failureThreshold }}
            {{- end }}
          {{- end }}
          {{- if .Values.node.readinessProbe.enabled }}
          readinessProbe:
            {{- if .Values.node.readinessProbe.customReadinessProbe }}
            {{- toYaml .Values.node.readinessProbe.customReadinessProbe | nindent 12 }}
            {{- else }}
            {{- if .Values.tls.enabled }}
            exec:
              command:
                - /bin/sh
                - -c
                - redis-cli --tls --cert {{ .Values.paths.tlsDir }}/{{ .Values.paths.tlsCertFile }} --key {{ .Values.paths.tlsDir }}/{{ .Values.paths.tlsKeyFile }} --cacert {{ .Values.paths.tlsDir }}/{{ .Values.paths.tlsCaCertFile }} -p {{ .Values.ports.cache }} ping
            {{- else }}
            tcpSocket:
              port: cache
            {{- end }}
            initialDelaySeconds: {{ .Values.node.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.node.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.node.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.node.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.node.readinessProbe.failureThreshold }}
            {{- end }}
          {{- end }}
          {{- if .Values.node.startupProbe.enabled }}
          startupProbe:
            {{- if .Values.node.startupProbe.customStartupProbe }}
            {{- toYaml .Values.node.startupProbe.customStartupProbe | nindent 12 }}
            {{- else }}
            {{- if .Values.tls.enabled }}
            exec:
              command:
                - /bin/sh
                - -c
                - redis-cli --tls --cert {{ .Values.paths.tlsDir }}/{{ .Values.paths.tlsCertFile }} --key {{ .Values.paths.tlsDir }}/{{ .Values.paths.tlsKeyFile }} --cacert {{ .Values.paths.tlsDir }}/{{ .Values.paths.tlsCaCertFile }} -p {{ .Values.ports.cache }} ping
            {{- else }}
            tcpSocket:
              port: cache
            {{- end }}
            initialDelaySeconds: {{ .Values.node.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.node.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.node.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.node.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.node.startupProbe.failureThreshold }}
            {{- end }}
          {{- end }}
          {{- if .Values.node.resources }}
          resources: {{- toYaml .Values.node.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: cache-data
              mountPath: /data
            - name: scripts
              mountPath: /scripts
            {{- if .Values.tls.enabled }}
            - name: tls-certs
              mountPath: {{ .Values.paths.tlsDir }}
              readOnly: true
            {{- end }}
            {{- if .Values.node.extraVolumeMounts }}
            {{- toYaml .Values.node.extraVolumeMounts | nindent 12 }}
            {{- end }}
        {{- if .Values.node.sidecars }}
        {{- toYaml .Values.node.sidecars | nindent 8 }}
        {{- end }}
      {{- if .Values.node.initContainers }}
      initContainers:
        {{- toYaml .Values.node.initContainers | nindent 8 }}
      {{- end }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "cache-ha.fullname" . }}-scripts
            defaultMode: 0755
        {{- if .Values.tls.enabled }}
        - name: tls-certs
          secret:
            secretName: {{ include "cache-ha.tlsSecretName" . }}
        {{- end }}
        {{- if .Values.node.extraVolumes }}
        {{- toYaml .Values.node.extraVolumes | nindent 8 }}
        {{- end }}
  {{- if .Values.node.persistentVolumeClaimRetentionPolicy.enabled }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .Values.node.persistentVolumeClaimRetentionPolicy.whenDeleted }}
    whenScaled: {{ .Values.node.persistentVolumeClaimRetentionPolicy.whenScaled }}
  {{- end }}
  {{- if .Values.node.persistence.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: cache-data
        labels: {{- include "cache-ha.labels" . | nindent 10 }}
          app.kubernetes.io/component: {{ .Values.componentNames.cache | default "cache" }}
        {{- if .Values.node.persistence.annotations }}
        annotations: {{- toYaml .Values.node.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- range .Values.node.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.node.persistence.size | quote }}
        {{- include "cache-ha.storageClass" . | nindent 8 }}
  {{- end }}
