{{- /*
Copyright Akeyless, Inc. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "cache-ha.fullname" . }}-sentinel
  namespace: {{ include "cache-ha.namespace" . }}
  labels: {{- include "cache-ha.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.componentNames.sentinel | default "sentinel" }}
  {{- if .Values.service.annotations }}
  annotations: {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  {{- include "cache-ha.commonAnnotations" . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP | quote }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range .Values.service.loadBalancerSourceRanges }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity | quote }}
  {{- end }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- toYaml .Values.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  ports:
    - name: sentinel
      port: {{ .Values.service.ports.sentinel }}
      targetPort: sentinel-port
      protocol: TCP
  selector: {{- include "cache-ha.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.componentNames.sentinel | default "sentinel" }}
