{{/*
Copyright Akeyless, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) }}
{{- $secretName := printf "%s-crt" (include "cache-ha.fullname" .) }}
{{- $ca := genCA "cache-ca" 365 }}
{{- $releaseNamespace := (include "cache-ha.namespace" .) }}
{{- $clusterDomain := .Values.clusterDomain | default "cluster.local" }}
{{- $fullname := include "cache-ha.fullname" . }}
{{- $serviceName := include "cache-ha.fullname" . }}
{{- $headlessServiceName := printf "%s-headless" (include "cache-ha.fullname" .) }}
{{- $cacheHeadlessServiceName := printf "%s-cache-headless" (include "cache-ha.fullname" .) }}
{{- $sentinelHeadlessServiceName := printf "%s-sentinel-headless" (include "cache-ha.fullname" .) }}
{{- $altNames := list 
  (printf "*.%s.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain) 
  (printf "%s.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain) 
  (printf "*.%s.%s.svc.%s" $headlessServiceName $releaseNamespace $clusterDomain) 
  (printf "%s.%s.svc.%s" $headlessServiceName $releaseNamespace $clusterDomain) 
  (printf "*.%s.%s.svc.%s" $cacheHeadlessServiceName $releaseNamespace $clusterDomain) 
  (printf "%s.%s.svc.%s" $cacheHeadlessServiceName $releaseNamespace $clusterDomain) 
  (printf "*.%s.%s.svc.%s" $sentinelHeadlessServiceName $releaseNamespace $clusterDomain) 
  (printf "%s.%s.svc.%s" $sentinelHeadlessServiceName $releaseNamespace $clusterDomain) 
  "127.0.0.1" 
  "localhost" 
  $fullname 
}}
{{- $cert := genSignedCert $fullname nil $altNames 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "cache-ha.namespace" . }}
  labels: {{- include "cache-ha.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end }}
