globalConfig:
  gatewayAuth:
    gatewayAccessType: access_key
    gatewayCredentialsExistingSecret: akeyless-auth

gateway:
  service:
    type: ClusterIP

sra:
  sshConfig:
    service:
      type: ClusterIP

gatewayAPI:
  enabled: true
  parentRefs:
    - name: shared-gw
      namespace: chart-testing
  httpRoutes:
    - hostname: gw.example.com
      servicePort: gateway
