globalConfig:
  gatewayAuth:
    gatewayAccessType: access_key
    gatewayCredentialsExistingSecret: akeyless-auth

gateway:
  service:
    type: ClusterIP

sra:
  sshConfig:
    service:
      type: ClusterIP

gatewayAPI:
  enabled: true
  gateway:
    create: true
    gatewayClassName: cilium
  backend:
    ports:
      - {name: gateway, port: 8000}
      - {name: kmip, port: 5696}
      - {name: hvp, port: 8200}
      - {name: ssh, port: 22}
      - {name: echo, port: 8080}
  httpRoutes:
    - hostname: echo.dataplane.test
      backendRefs:
        - {servicePort: echo, serviceName: gwapi-echo}
