{{- if and (.Values.gateway.secretsStore.enabled) (not .Values.gateway.secretsStore.provider.existingClass) }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ required "secretProviderClassName is required" .Values.gateway.secretsStore.provider.secretProviderClassName | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: {{ .Values.gateway.secretsStore.provider.type | quote }}
  parameters:
    {{- if eq .Values.gateway.secretsStore.provider.type "aws" }}
    # AWS region where secrets are stored
    region: {{ .Values.gateway.secretsStore.provider.aws.region }}
    # Optional: Failover region for high availability
    {{- if .Values.gateway.secretsStore.provider.aws.failoverRegion }}
    failoverRegion: {{ .Values.gateway.secretsStore.provider.aws.failoverRegion }}
    {{- end }}
    # Optional: Use FIPS endpoint
    {{- if .Values.gateway.secretsStore.provider.aws.useFipsEndpoint }}
    useFipsEndpoint: {{ .Values.gateway.secretsStore.provider.aws.useFipsEndpoint }}
    {{- end }}
    # Optional: Pod identity endpoint type (ipv4, ipv6, or auto)
    {{- if .Values.gateway.secretsStore.provider.aws.podIdentityEndpointType }}
    podIdentityEndpointType: {{ .Values.gateway.secretsStore.provider.aws.podIdentityEndpointType }}
    {{- end }}
    # List of secrets to fetch from AWS Secrets Manager and SSM Parameter Store
    objects: |
      {{ .Values.gateway.secretsStore.provider.aws.objects | nindent 6 }}
    {{- end }}
    {{- if eq .Values.gateway.secretsStore.provider.type "azure" }}
    # Azure Key Vault name
    keyvaultName: {{ .Values.gateway.secretsStore.provider.azure.keyvaultName }}
    # Azure Tenant ID
    tenantID: {{ .Values.gateway.secretsStore.provider.azure.tenantID }}
    # Optional: Use pod identity for authentication
    {{- if .Values.gateway.secretsStore.provider.azure.usePodIdentity }}
    usePodIdentity: {{ .Values.gateway.secretsStore.provider.azure.usePodIdentity }}
    {{- end }}
    # Optional: Use VM managed identity
    {{- if .Values.gateway.secretsStore.provider.azure.useVMManagedIdentity }}
    useVMManagedIdentity: {{ .Values.gateway.secretsStore.provider.azure.useVMManagedIdentity }}
    {{- end }}
    # Optional: User assigned identity ID
    {{- if .Values.gateway.secretsStore.provider.azure.userAssignedIdentityID }}
    userAssignedIdentityID: {{ .Values.gateway.secretsStore.provider.azure.userAssignedIdentityID }}
    {{- end }}
    # Optional: Client ID for workload identity
    {{- if .Values.gateway.secretsStore.provider.azure.clientID }}
    clientID: {{ .Values.gateway.secretsStore.provider.azure.clientID }}
    {{- end }}
    # Optional: Azure cloud name (AzurePublicCloud, AzureUSGovernmentCloud, etc.)
    {{- if .Values.gateway.secretsStore.provider.azure.cloudName }}
    cloudName: {{ .Values.gateway.secretsStore.provider.azure.cloudName }}
    {{- end }}
    # Optional: File permission for mounted secrets (default: 0644)
    {{- if .Values.gateway.secretsStore.provider.azure.filePermission }}
    filePermission: {{ .Values.gateway.secretsStore.provider.azure.filePermission }}
    {{- end }}
    # List of objects to fetch from Azure Key Vault
    objects: |
      {{ .Values.gateway.secretsStore.provider.azure.objects | nindent 6 }}
    {{- end }}
    {{- if eq .Values.gateway.secretsStore.provider.type "gcp" }}
    # GCP project ID
    projectID: {{ .Values.gateway.secretsStore.provider.gcp.projectID }}
    # Optional: File permission for mounted secrets (default: 0644)
    {{- if .Values.gateway.secretsStore.provider.gcp.filePermission }}
    filePermission: {{ .Values.gateway.secretsStore.provider.gcp.filePermission }}
    {{- end }}
    # List of secrets to fetch from GCP Secret Manager
    secrets: |
      {{- .Values.gateway.secretsStore.provider.gcp.secrets | nindent 6 }}
    {{- end }}
    {{- if eq .Values.gateway.secretsStore.provider.type "akeyless" }}
    # Akeyless API URL
    url: {{ .Values.gateway.secretsStore.provider.akeyless.url }}
    # Access ID for authentication
    accessId: {{ .Values.gateway.secretsStore.provider.akeyless.accessId }}
    # Optional: Access Key for authentication
    {{- if .Values.gateway.secretsStore.provider.akeyless.accessKey }}
    accessKey: {{ .Values.gateway.secretsStore.provider.akeyless.accessKey }}
    {{- end }}
    # Optional: JWT for authentication
    {{- if .Values.gateway.secretsStore.provider.akeyless.jwt }}
    jwt: {{ .Values.gateway.secretsStore.provider.akeyless.jwt }}
    {{- end }}
    # Optional: File permission for mounted secrets (default: 0644)
    {{- if .Values.gateway.secretsStore.provider.akeyless.filePermission }}
    filePermission: {{ .Values.gateway.secretsStore.provider.akeyless.filePermission }}
    {{- end }}
    # List of objects to fetch from Akeyless
    objects: |
      {{ .Values.gateway.secretsStore.provider.akeyless.objects | nindent 6 }}
    {{- end }}
    {{- end }} 