apiVersion: v2
name: akeyless-csi-provider
description: A Helm chart for Kubernetes that deploys akeyless-csi-provider
maintainers:
  - name: Akeyless
    email: support@akeyless.io
    url: https://www.akeyless.io
version: 1.0.4
appVersion: 1.0.0
kubeVersion: ">= 1.14.0-0"
sources:
  - https://github.com/akeylesslabs/akeyless-csi-provider
