# Default values for cache-ha
# Simple Cache Sentinel High Availability

# Global settings
global:
  imageRegistry: ""
  imagePullSecrets: []
  # Default storage class (required if cache.persistence.storageClass is not set)
  defaultStorageClass: ""

# Image configuration
image:
  registry: docker.io
  repository: redis
  tag: 8.2.1-alpine3.22
  pullPolicy: IfNotPresent

# Node configuration
node:
  # Number of Redis nodes (each runs Redis + Sentinel)
  replicaCount: 3
  
  
  # Resources
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  # Storage
  persistence:
    enabled: true
    size: 8Gi
    # Storage class (if not set, will use global.defaultStorageClass)
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    annotations: {}
  
  # Ports
  ports:
    cache: 6379
    sentinel: 26379
  
  # Pod configuration
  podLabels: {}
  podAnnotations: {}
  podSecurityContext:
    enabled: false
    fsGroup: 1001
  containerSecurityContext:
    enabled: false
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  
  # Probes
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
    customLivenessProbe: {}
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 5
    customReadinessProbe: {}
  startupProbe:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 15
    customStartupProbe: {}
  
  # StatefulSet configuration
  revisionHistoryLimit: 10
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  persistentVolumeClaimRetentionPolicy:
    enabled: false
    whenDeleted: Delete
    whenScaled: Delete
  
  # Pod configuration
  affinity: {}
  # affinity:
  #   # Pod anti-affinity example - spread cache pods across different nodes
  #   podAntiAffinity:
  #     preferredDuringSchedulingIgnoredDuringExecution:
  #     - weight: 100
  #       podAffinityTerm:
  #         labelSelector:
  #           matchExpressions:
  #           - key: app.kubernetes.io/component
  #             operator: In
  #             values:
  #             - cache
  #         topologyKey: kubernetes.io/hostname
  #   # Pod affinity example - ensure cache pods are co-located with sentinel pods
  #   podAffinity:
  #     preferredDuringSchedulingIgnoredDuringExecution:
  #     - weight: 50
  #       podAffinityTerm:
  #         labelSelector:
  #           matchExpressions:
  #           - key: app.kubernetes.io/component
  #             operator: In
  #             values:
  #             - sentinel
  #         topologyKey: kubernetes.io/hostname
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  # topologySpreadConstraints:
  # - maxSkew: 1
  #   topologyKey: kubernetes.io/hostname
  #   whenUnsatisfiable: DoNotSchedule
  #   labelSelector:
  #     matchExpressions:
  #     - key: app.kubernetes.io/component
  #       operator: In
  #       values:
  #       - cache
  priorityClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: 30
  dnsPolicy: ""
  dnsConfig: {}
  hostAliases: []
  shareProcessNamespace: false
  automountServiceAccountToken: true
  enableServiceLinks: true
  
  # Extra configuration
  extraFlags: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraVolumes: []
  extraVolumeMounts: []
  sidecars: []
  initContainers: []
  lifecycleHooks: {}
  # Pod Disruption Budget
  pdb:
    enabled: false
    minAvailable: ""
    maxUnavailable: 1

# Network Policy
networkPolicy:
  enabled: false
  ingressRules: []
  egressRules: []

# Sentinel configuration
sentinel:
  # Number of sentinel instances (defaults to node replicaCount if not set)
  replicaCount: 3
  
  # Master set name
  masterSet: "mymaster"
  
  # Sentinel quorum is calculated automatically using formula: (sentinel_count / 2) + 1
  # This ensures majority consensus among sentinels for failover decisions
  # Examples:
  #   - 3 sentinels → quorum = 2
  #   - 5 sentinels → quorum = 3  
  #   - 7 sentinels → quorum = 4
  
  # Timeouts
  downAfterMilliseconds: 10000  # Increased from 3000ms to 10s for better Kubernetes tolerance
  failoverTimeout: 15000        # Increased from 5000ms to 15s for better Kubernetes tolerance
  parallelSyncs: 2
  
  # Sentinel-specific pod configuration (inherits from cache if not set)
  podLabels: {}
  podAnnotations: {}
  podSecurityContext:
    enabled: false
    fsGroup: 1001
  containerSecurityContext:
    enabled: false
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  
  # Sentinel-specific probes (inherits from cache if not set)
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
    customLivenessProbe: {}
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 5
    customReadinessProbe: {}
  
  # Sentinel-specific StatefulSet configuration
  revisionHistoryLimit: 10
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  persistentVolumeClaimRetentionPolicy:
    enabled: false
    whenDeleted: Delete
    whenScaled: Delete
  
  # Sentinel-specific pod configuration
  affinity: {}
  # affinity:
  #   # Pod anti-affinity example - spread sentinel pods across different nodes
  #   podAntiAffinity:
  #     preferredDuringSchedulingIgnoredDuringExecution:
  #     - weight: 100
  #       podAffinityTerm:
  #         labelSelector:
  #           matchExpressions:
  #           - key: app.kubernetes.io/component
  #             operator: In
  #             values:
  #             - sentinel
  #         topologyKey: kubernetes.io/hostname
  #   # Pod affinity example - ensure sentinel pods are co-located with cache pods
  #   podAffinity:
  #    preferredDuringSchedulingIgnoredDuringExecution:
  #    - weight: 50
  #      podAffinityTerm:
  #        labelSelector:
  #          matchExpressions:
  #          - key: app.kubernetes.io/component
  #            operator: In
  #            values:
  #            - cache
  #        topologyKey: kubernetes.io/hostname
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  # topologySpreadConstraints:
  # - maxSkew: 1
  #   topologyKey: kubernetes.io/hostname
  #   whenUnsatisfiable: DoNotSchedule
  #   labelSelector:
  #     matchExpressions:
  #     - key: app.kubernetes.io/component
  #       operator: In
  #       values:
  #       - sentinel
  priorityClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: 30
  dnsPolicy: ""
  dnsConfig: {}
  hostAliases: []
  shareProcessNamespace: false
  automountServiceAccountToken: true
  enableServiceLinks: true
  
  # Sentinel-specific resources
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  # Extra configuration
  extraFlags: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraVolumes: []
  extraVolumeMounts: []
  sidecars: []
  initContainers: []
  lifecycleHooks: {}
  
  # Pod Disruption Budget
  pdb:
    enabled: false
    minAvailable: ""
    maxUnavailable: 1

# Authentication
auth:
  enabled: false
  password: ""

# TLS configuration
tls:
  enabled: false
  authClients: false
  existingSecret: ""

# Paths configuration
paths:
  configDir: /etc/cache
  configFile: cache.conf
  sentinelConfigFile: sentinel.conf
  tlsDir: /etc/cache/tls
  tlsCertFile: tls.crt
  tlsKeyFile: tls.key
  tlsCaCertFile: ca.crt


# Service configuration
service:
  type: ClusterIP
  ports:
    cache: 6379
    sentinel: 26379
  annotations: {}
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  clusterIP: ""
  sessionAffinity: ""
  sessionAffinityConfig: {}

# Headless service for StatefulSet (required for Sentinel)
headless:
  service:
    clusterIP: None
    ports:
      cache: 6379
      sentinel: 26379
    annotations: {}

# Service account
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""


# Secret configuration
secretAnnotations: {}

# Common labels and annotations
commonLabels: {}
commonAnnotations: {}

# Component names (configurable)
componentNames:
  cache: "cache"
  sentinel: "sentinel"

# Namespace override
namespaceOverride: ""

# Name overrides
nameOverride: ""
fullnameOverride: ""

# Log level configuration (suppress SSL errors when set to warning)
logLevel: "warning"  # notice, warning, verbose, debug