apiVersion: v1
kind: Secret
metadata:
    name: akeyless-docker-hub-ssh
    annotations:
        "helm.sh/hook": pre-install
        "helm.sh/hook-delete-policy": before-hook-creation
    namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ required "A valid .Values.conf.dockerRepositoryCreds entry required!" .Values.image.dockerRepositoryCreds }}
type: kubernetes.io/dockerconfigjson
