---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "akeyless-ssh-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "akeyless-ssh-proxy.labels" . | nindent 4 }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ required "A valid .Values.service.type entry required!" .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
    - port: {{ .Values.service.curlProxyPort }}
      targetPort: curl-proxy
      protocol: TCP
      name: curl-proxy
  selector:
    {{- include "akeyless-ssh-proxy.selectorLabels" . | nindent 4 }}