apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-cm-akeyless
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $.Values.dispatcher.containerName }}
    chart: {{ $.Chart.Name }}
data:
{{ with .Values.dispatcher.config }}
  {{- if (ne (include "secret-exist" (dict "Root" $.Values.dispatcher.config.privilegedAccess.existingSecretNames "Name" "access")) "true") }}
  akeyless_config_file: |
    {{ required "API Gateway URL is required" .apiGatewayURL }}
    cmd=auth&access-id={{ .listOnlyCredentials.samlAccessID }}
    cmd=auth&access-id={{ required "Privileged credentials are required" .privilegedAccess.accessID }}&access-key={{ .privilegedAccess.accessKey }}
    {{- end }}
{{- end}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-cm-web-policies
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $.Values.webWorker.containerName }}
    chart: {{ $.Chart.Name }}
data:
  policies.json: |
{{ required "A valid .Values.webWorker.config.policies entry required!" .Values.webWorker.config.policies | indent 4 }}


{{- if .Values.dlp.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-cm-dlp-conf
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ $.Chart.Name }}
data:
  dlp.conf: |
    host={{ .Values.dlp.config.hostAddress | quote }}
    path_prefix={{ .Values.dlp.config.pathPrefix | quote }}
    mode={{ .Values.dlp.config.mode | quote }}
    log_level={{ .Values.dlp.config.logLevel | quote }}

{{- if not .Values.dlp.existingLogForwardSecretName }}
    {{ if .Values.dlp.audit }}
  logand.conf: |
{{ .Values.dlp.audit | indent 4 }}
{{- end }}
{{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-cm-akeyless-config
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ $.Chart.Name }}
data:
{{- if not .Values.dispatcher.config.existingLogForwardSecretName  }}
{{ if .Values.dispatcher.config.logForward }}
  logand.conf: |
{{ .Values.dispatcher.config.logForward | indent 4 }}
{{- end }}
{{- end }}