apiVersion: v1
kind: Service
metadata:
  name:  {{ include "akeyless-zero-web-access.fullname" . }}-metric-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: dispatcher-metric-svc
spec:
  type: ClusterIP
  ports:
    - name: metrics # expose metrics port
      port: 2000
      targetPort: metrics
      protocol: TCP
  selector:
    app: dispatcher
