{{- if .Values.HPA.enabled }}
apiVersion: {{ include "hpa.api.version" $ }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Release.Name }}-hpa-dispatcher
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-dispatcher-deployment
  minReplicas: {{ $.Values.HPA.dispatcher.minReplicas | default 1 }}
  maxReplicas: {{ $.Values.HPA.dispatcher.maxReplicas | default 14 }}
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.HPA.dispatcher.memAvgUtil }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.HPA.dispatcher.cpuAvgUtil }}


{{- if .Values.metrics.enabled }}
---
apiVersion: {{ include "hpa.api.version" $ }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Release.Name }}-hpa-web-worker
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-worker-deployment
  minReplicas: {{ $.Values.HPA.webWorker.minReplicas | default 3 }}
  maxReplicas: {{ $.Values.HPA.webWorker.maxReplicas | default 14 }}
  metrics:
    - type: Object
      object:
        metric:
          name: workers_utilization
        describedObject:
          apiVersion: v1
          kind: Service
          name: {{ include "akeyless-zero-web-access.fullname" . }}-metric-svc
        target:
          type: Value
          value: {{ $.Values.HPA.webWorker.busyWorkersPercentage }}

{{- end }}
{{- end }}
