{{- if .Values.image.dockerRepositoryCreds }}
apiVersion: v1
kind: Secret
metadata:
  name: akeyless-docker-hub-web-access
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": pre-install
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.image.dockerRepositoryCreds }}
type: kubernetes.io/dockerconfigjson
{{- end }}
