apiVersion: v1
kind: Secret
metadata:
    name: akeyless-docker-hub
    annotations:
      "helm.sh/hook-delete-policy": before-hook-creation
      "helm.sh/hook": pre-install
    namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ required "A valid .Values.conf.dockerconfigjson entry required!" .Values.image.dockerRepositoryCreds }}
type: kubernetes.io/dockerconfigjson
