{{- if eq .Values.sshConfig.enabled true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-cm-creds
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $.Values.sshConfig.containerName }}
    chart: {{ $.Chart.Name }}
data:
  ca.pub: |
{{ required "A valid .Values.sshConfig.conf.CAPublicKey entry required!" .Values.sshConfig.config.CAPublicKey | indent 4 }}

{{- if .Values.sshConfig.config.sessionTermination.enabled }}
  api-url: |
{{ .Values.sshConfig.config.sessionTermination.apiURL | indent 4  }}
  api-token: |
{{ .Values.sshConfig.config.sessionTermination.apiToken | indent 4  }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-cm-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $.Values.sshConfig.containerName }}
    chart: {{ $.Chart.Name }}
data:
  {{- with .Values.sshConfig.config.logForwarding}}
  {{- if .enabled }}
  logand.conf: |
  {{- if .existingSecretName }}
  {{- include "getValueFromSecret" (dict "Namespace" $.Release.Namespace "Name" .existingSecretName "Key" "settings") | nindent 4 -}}
  {{- else }}
  {{- required "A valid .Values.sshConfig.config.logForwarding.settings entry required!" .settings | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
  akeyless_config_file: |
    {{ required "API Gateway URL is required" .Values.apiGatewayURL }}
    {{- with .Values.privilegedAccess}}
    {{- if .existingSecretName }}
    {{- $accessID := include "getValueFromSecret" (dict "Namespace" $.Release.Namespace "Name" .existingSecretName "Key" "accessID") }}
    {{- $accessKey := include "getValueFromSecret" (dict "Namespace" $.Release.Namespace "Name" .existingSecretName "Key" "accessKey")}}
    cmd=auth&access-id={{ required "Privileged access credentials are required" $accessID }}&access-key={{ $accessKey }}
    {{- else}}
    cmd=auth&access-id={{ required "Privileged access credentials are required" .accessID }}&access-key={{ .accessKey }}
    {{- end }}
    {{- end }}
{{- end }}