{{- if .Values.ztbConfig.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-{{ include "akeyless-secure-remote-access.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "akeyless-secure-remote-access.labels" . | nindent 4 }}
  {{- if .Values.deployment.labels }}
    {{- toYaml .Values.deployment.labels | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: zero-trust-bastion
  {{- if not .Values.ztbConfig.HPA.enabled }}
  replicas: {{ .Values.ztbConfig.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        app: zero-trust-bastion
    spec:
      {{- if .Values.sshConfig.securityContext }}
        {{- if .Values.sshConfig.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.sshConfig.securityContext.runAsUser }}
        fsGroup: {{ .Values.sshConfig.securityContext.fsGroup }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ template "akeyless-api-gw.getServiceAccountName" . }}
      {{- if .Values.sshConfig.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.sshConfig.nodeSelector | indent 4 }}
      {{- end }}
      imagePullSecrets:
        - name: akeyless-docker-hub
      volumes:
          {{- range .Values.ztbConfig.persistence.volumes }}
        - name: {{ .name | title | lower }}
          persistentVolumeClaim:
            claimName: {{ printf "%s-%s" $.Release.Name .name | title | lower }}
          {{- end }}
      containers:
        - name: {{ .Values.ztbConfig.containerName }}
          image: "{{ .Values.ztbConfig.image.repository }}:{{ .Values.ztbConfig.image.tag | default .Chart.Annotations.ztbVersion }}"
          imagePullPolicy: {{ .Values.ztbConfig.image.pullPolicy }}
          ports:
            - containerPort: 8888
              name: api
          env:
            - name: BASTION_API
              value: "ssh-{{ include "akeyless-secure-remote-access.fullname" . }}:{{ .Values.sshConfig.service.curlProxyPort }}"
            - name: BASTION_SSH
              value: "ssh-{{ include "akeyless-secure-remote-access.fullname" . }}:{{ .Values.sshConfig.service.port }}"
{{- if .Values.apiGatewayURL }}
            - name: AKEYLESS_URL
              value: {{ .Values.apiGatewayURL }}
{{- end }}
{{- if .Values.clusterName }}
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName }}
{{- end }}
{{- if .Values.legacySigningAlg }}
            - name: LEGACY_SIGNING_ALG
              value: {{ .Values.legacySigningAlg | quote }}
{{- end }}
{{- if .Values.usernameSubClaim }}
            - name: USERNAME_SUB_CLAIM
              value: {{ .Values.usernameSubClaim }}
{{- end }}
{{- if .Values.ztbConfig.allowedBastionUrls }}
            - name: ALLOWED_BASTION_URLS
              value: {{ range $index, $element := .Values.ztbConfig.allowedBastionUrls -}}{{- if $index -}},{{- end -}}{{ $element }}{{ end }}
{{- end }}
{{- with .Values.privilegedAccess }}
            - name: PRIVILEGED_ACCESS_ID
              value: {{ required "Privileged access ID is required" .accessID }}
  {{- if .accessKey }}
            - name: PRIVILEGED_ACCESS_KEY
              value: {{ .accessKey }}
  {{- end }}
  {{- if .allowedAccessIDs }}
            - name: ALLOWED_ACCESS_IDS
              value: {{ range $index, $element := .allowedAccessIDs -}}{{- if $index -}},{{- end -}}{{ $element }}{{ end }}
  {{- end }}
  {{- if .azureObjectID }}
            - name: AZURE_OBJECT_ID
              value: {{ .azureObjectID }}
  {{- end }}
  {{- if .gcpAudience }}
            - name: GCP_AUDIENCE
              value: {{ .gcpAudience }}
  {{- end }}
{{- end }}
{{- if .Values.ztbConfig.config.rdpRecord.enabled }}
  {{- if .Values.ztbConfig.config.rdpRecord.s3.bucketName }}
            - name: AWS_REGION
              value: {{ required "A valid .Values.ztbConfig.config.rdpRecord.s3.region required!" .Values.ztbConfig.config.rdpRecord.s3.region }}
            - name: AWS_S3_BUCKET
              value: {{ required "A valid .Values.ztbConfig.config.rdpRecord.s3.bucketName required!" .Values.ztbConfig.config.rdpRecord.s3.bucketName }}
            - name: AWS_S3_PREFIX
              value: {{ required "A valid .Values.ztbConfig.config.rdpRecord.s3.bucketPrefix required!" .Values.ztbConfig.config.rdpRecord.s3.bucketPrefix }}
  {{- end }}
  {{- if or ( .Values.ztbConfig.config.rdpRecord.s3.awsAccessKeyId) ( .Values.ztbConfig.config.rdpRecord.existingSecret) }}
        {{- if .Values.ztbConfig.config.rdpRecord.s3.bucketName }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "akeyless-zero-trust-bastion.secretName" . }}
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "akeyless-zero-trust-bastion.secretName" . }}
                  key: aws-secret-access-key
        {{- end }}
  {{- end }}
  {{- if .Values.ztbConfig.config.rdpRecord.azure.storageAccountName }}
            - name: AZURE_STORAGE_ACCOUNT
              value: {{ required "A valid .Values.ztbConfig.config.rdpRecord.azure.storageAccountName required!" .Values.ztbConfig.config.rdpRecord.azure.storageAccountName }}
            - name: AZURE_STORAGE_CONTAINER_NAME
              value: {{ required "A valid .Values.ztbConfig.config.rdpRecord.azure.storageContainerName required!" .Values.ztbConfig.config.rdpRecord.azure.storageContainerName }}
  {{- end }}
  {{- if or ( .Values.ztbConfig.config.rdpRecord.azure.azureClientId) ( .Values.ztbConfig.config.rdpRecord.existingSecret) }}
        {{- if .Values.ztbConfig.config.rdpRecord.azure.storageAccountName }}
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "akeyless-zero-trust-bastion.secretName" . }}
                  key: azure-client-id
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "akeyless-zero-trust-bastion.secretName" . }}
                  key: azure-client-secret
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "akeyless-zero-trust-bastion.secretName" . }}
                  key: azure-tenant-id
          {{- end }}
  {{- end }}
  {{- if .Values.httpProxySettings.http_proxy }}
            - name: http_proxy
              value: {{ .Values.httpProxySettings.http_proxy }}
  {{- end }}
  {{- if .Values.httpProxySettings.https_proxy }}
            - name: https_proxy
              value: {{ .Values.httpProxySettings.https_proxy }}
  {{- end }}
  {{- if .Values.httpProxySettings.no_proxy }}
            - name: no_proxy
              value: {{ .Values.httpProxySettings.no_proxy }}
  {{- end }}
  {{- if .Values.ztbConfig.config.rdpRecord.keepLocalRecording }}
            - name: KEEP_LOCAL_RECORDINGS
              value: "true"
  {{- end }}
{{- end }}
{{- if .Values.ztbConfig.env }}
{{- toYaml .Values.ztbConfig.env | nindent 12 }}
{{- end }}
          resources:
{{- toYaml .Values.ztbConfig.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 8888
{{- toYaml .Values.ztbConfig.livenessProbe | trim | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: 8888
{{- toYaml .Values.ztbConfig.readinessProbe | trim | nindent 12 }}
          volumeMounts:
          {{- range .Values.ztbConfig.persistence.volumes }}
            - name: {{ .name | title | lower }}
              mountPath: /home/akeyless/recordings
              subPath: recordings
          {{- end }}
{{- end }}
