{{- if eq .Values.sshConfig.enabled true }}
{{- if .Values.sshConfig.HPA.enabled }}
apiVersion: {{ include "hpa.api.version" $ }}
kind: HorizontalPodAutoscaler
metadata:
  name: ssh-{{ $.Release.Name }}-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: ssh-{{ include "akeyless-secure-remote-access.fullname" . }}
  minReplicas: {{ $.Values.sshConfig.HPA.minReplicas | default 1 }}
  maxReplicas: {{ $.Values.sshConfig.HPA.maxReplicas | default 14 }}
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.sshConfig.HPA.memAvgUtil }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.sshConfig.HPA.cpuAvgUtil }}
{{- end }}
{{- end }}
---
{{- if eq .Values.ztbConfig.enabled true }}
{{- if .Values.ztbConfig.HPA.enabled }}
apiVersion: {{ include "hpa.api.version" $ }}
kind: HorizontalPodAutoscaler
metadata:
  name: ztb-{{ $.Release.Name }}-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "akeyless-secure-remote-access.fullname" . }}
  minReplicas: {{ $.Values.ztbConfig.HPA.minReplicas | default 1 }}
  maxReplicas: {{ $.Values.ztbConfig.HPA.maxReplicas | default 14 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.ztbConfig.HPA.cpuAvgUtil }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.ztbConfig.HPA.memAvgUtil }}
{{- end }}
{{- end }}