{{- if eq .Values.ztbConfig.enabled true }}
{{- if .Values.ztbConfig.ingress.enabled }}
apiVersion: {{ include "checkIngressVersion.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "akeyless-secure-remote-access.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "akeyless-secure-remote-access.labels" . | nindent 4 }}
  {{- if .Values.ztbConfig.ingress.labels }}
    {{- toYaml .Values.ztbConfig.ingress.labels | nindent 4 }}
  {{- end }}
  annotations:
{{- if .Values.ztbConfig.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
{{- end }}
{{- if .Values.ztbConfig.ingress.annotations }}
{{ toYaml .Values.ztbConfig.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
{{- if .Values.ztbConfig.ingress.hostname }}
  - host: {{ .Values.ztbConfig.ingress.hostname }}
    http:
      paths:
      - path: {{ .Values.ztbConfig.ingress.path }}
{{- if eq (include "checkIngressVersion.ingress.apiVersion" . ) "networking.k8s.io/v1" }}
        pathType: ImplementationSpecific
        backend:
         service:
          name: web-{{ include "akeyless-secure-remote-access.fullname" . }}
          port:
            name: api
{{- else }}
        backend:
         serviceName: web-{{ include "akeyless-secure-remote-access.fullname" . }}
         servicePort: api
{{- end }}
{{- end }}
{{- if .Values.ztbConfig.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ztbConfig.ingress.hostname }}
      secretName: {{ template "akeyless-zero-trust-bastion.ingressSecretTLSName" . }}
{{- end }}
{{- end }}
{{- end }}