apiVersion: v1
kind: Secret
metadata:
    name: akeyless-docker-hub
    annotations:
        "helm.sh/hook": pre-install
        "helm.sh/hook-delete-policy": before-hook-creation
    namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ required "A valid .Values.dockerRepositoryCreds entry required!" .Values.dockerRepositoryCreds }}
type: kubernetes.io/dockerconfigjson
---
{{- if eq .Values.ztbConfig.enabled true }}
{{ if and (not .Values.ztbConfig.config.rdpRecord.existingSecret) (or (.Values.ztbConfig.config.rdpRecord.s3.awsAccessKeyId) (.Values.ztbConfig.config.rdpRecord.azure.azureClientId)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-secure-remote-access.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "akeyless-secure-remote-access.name" . }}
    chart: {{ include "akeyless-secure-remote-access.chart" . }}
    release: "{{ .Release.Name }}"
type: Opaque
data:
  {{ if .Values.ztbConfig.config.rdpRecord.s3.awsAccessKeyId }}
  aws-access-key-id: {{ .Values.ztbConfig.config.rdpRecord.s3.awsAccessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ .Values.ztbConfig.config.rdpRecord.s3.awsSecretAccessKey | b64enc | quote }}
  {{- end }}
  {{ if .Values.ztbConfig.config.rdpRecord.azure.azureClientId }}
  azure-client-id: {{ .Values.ztbConfig.config.rdpRecord.azure.azureClientId | b64enc | quote }}
  azure-client-secret: {{ .Values.ztbConfig.config.rdpRecord.azure.azureClientSecret | b64enc | quote }}
  azure-tenant-id: {{ .Values.ztbConfig.config.rdpRecord.azure.azureTenantId | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}