{{ $global := . }}
{{- with .Values.sshConfig.service_account }}
{{- if .enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccountName }}
  namespace: {{ $global.Release.Namespace | quote }}
  annotations:
    {{ toYaml .annotations | indent 2 }}
{{- end -}}
{{- end -}}