{{ $global := . }}
{{ with .Values.privilegedAccess.service_account }}
{{- if (.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "akeyless-api-gw.getServiceAccountName" $ }}
  namespace: {{ $global.Release.Namespace | quote }}
  {{- if .annotations }}
  annotations:
    {{ toYaml .annotations | indent 2 }}
  {{- end -}}
{{- end -}}
{{- end -}}