{{- if .Values.sshConfig.service_account }}
{{ with .Values.sshConfig.service_account }}
{{- if (.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "akeyless-api-gw.getServiceAccountName" $ }}
  namespace: {{ $.Release.Namespace | quote }}
  {{- if .annotations }}
  annotations:
    {{ toYaml .annotations | indent 2 }}
  {{- end -}}
{{- end -}}
{{- end -}}
{{- else if .Values.privilegedAccess.serviceAccount }}
{{ with .Values.privilegedAccess.serviceAccount }}
{{- if (.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "akeyless-api-gw.getServiceAccountName" $ }}
  namespace: {{ $.Release.Namespace | quote }}
  {{- if .annotations }}
  annotations:
    {{ toYaml .annotations | indent 2 }}
  {{- end -}}
{{- end -}}
{{- end -}}
{{- end }}