{{- if (include "cacheEnableTls" . | eq "true") }}
{{- $fullname := .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- $ca := genCA "redis-ca" 365 }}
{{- $altNames := list $fullname (include "cacheAddress" .) (printf "*.%s" (include "cacheSvcName" . ))}}
{{- $cert := genSignedCert $fullname nil $altNames 365 $ca }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (include "generatedCacheTlsSecretName" .)).data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generatedCacheTlsSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ include "generatedCacheTlsSecretName" . }}
    component: cache
{{- include "akeyless-api-gw.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ get $existingSecret "tls.crt" | default ($cert.Cert | b64enc) }}
  tls.key: {{ get $existingSecret "tls.key" | default ($cert.Key | b64enc) }}
  ca.crt: {{ get $existingSecret "ca.crt" | default ($ca.Cert | b64enc) }}
{{- end }}
