{{- if .Values.customerFragments }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-cm-akeyless-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $.Values.containerName }}
    chart: {{ $.Chart.Name }}
data:
  customer_fragments.json: |
{{ .Values.customerFragments | indent 4 }}
{{- end }}
