---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "akeyless-services.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "akeyless-services.labels" . | nindent 4 }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.enabled }}
  type: NodePort
  {{- else }}
  type: {{ required "A valid .Values.service.type entry required!" .Values.service.type }}
  {{- end }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "akeyless-services.selectorLabels" . | nindent 4 }}