apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app: aks-akeyless-secrets-injection
    chart: akeyless-secrets-injection-1.2.27
    component: mutating-webhook
    release: aks
  name: aks-akeyless-secrets-injection
  namespace: akeyless
