apiVersion: v1
data:
  caCert: replaceMe with a CA cert that is base64 encoded
  servingCert: replaceMe with a signing certificate that is base64 encoded
  servingKey: replaceMe with a serving key that is base64 encoded
kind: Secret
metadata:
  name: aks-akeyless-secrets-injection
