apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: akeyless-secrets-injection
    chart: akeyless-secrets-injection-1.2.27
    component: mutating-webhook
    release: aks
  name: aks-akeyless-secrets-injection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akeyless-secrets-injection
      release: aks
  template:
    metadata:
      labels:
        app: akeyless-secrets-injection
        release: aks
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: akeyless-secrets-injection
                    release: aks
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - env:
            - name: TLS_CERT_FILE
              value: /var/serving-cert/servingCert
            - name: TLS_PRIVATE_KEY_FILE
              value: /var/serving-cert/servingKey
            - name: INTERNAL_PORT
              value: "8443"
            - name: DEBUG
              value: "false"
            - name: AKEYLESS_AGENT_IMAGE
              value: akeyless/k8s-secrets-sidecar:0.20.23
            - name: AKEYLESS_ACCESS_ID
              value: replaceMe
            - name: AKEYLESS_ACCESS_TYPE
              value: k8s
            - name: AKEYLESS_AGENT_LIMITS_CPU
              value: 500m
            - name: AKEYLESS_AGENT_LIMITS_MEM
              value: 128Mi
            - name: AKEYLESS_AGENT_REQUESTS_CPU
              value: 250m
            - name: AKEYLESS_AGENT_REQUESTS_MEM
              value: 64Mi
            - name: AKEYLESS_API_GW_URL
              value: replaceMe-with-url-to-gateway-8080-port
            - name: AKEYLESS_K8S_AUTH_CONF_NAME
              value: replaceMe
            - name: AKEYLESS_URL
              value: https://vault.akeyless.io
          image: akeyless/k8s-webhook-server:0.20.23
          imagePullPolicy: Always
          name: akeyless-secrets-injection
          ports:
            - containerPort: 8443
          resources:
            limits:
              cpu: 500m
              memory: 192Mi
            requests:
              cpu: 250m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 65534
          volumeMounts:
            - mountPath: /var/serving-cert
              name: serving-cert
      serviceAccountName: aks-akeyless-secrets-injection
      volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: aks-akeyless-secrets-injection
