apiVersion: v1
kind: Service
metadata:
  labels:
    app: aks-akeyless-secrets-injection
    chart: akeyless-secrets-injection-1.2.28
    component: mutating-webhook
    release: aks
  name: aks-akeyless-secrets-injection
spec:
  ports:
    - name: secrets-webhook
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: akeyless-secrets-injection
    release: aks
  type: ClusterIP
