apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: aks-akeyless-secrets-injection
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: replaceMe with a CA Bundle that is base64 encoded
      service:
        name: aks-akeyless-secrets-injection
        namespace: akeyless
        path: /pods
    failurePolicy: Ignore
    name: pods.akeyless-secrets-injection.admission
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values:
            - akeyless
    objectSelector:
      matchExpressions:
        - key: release
          operator: NotIn
          values:
            - aks
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
