{{ $ca := genCA "webhook-ca" 3650 }}
{{ $svcName := include "vault-secrets-webhook.fullname" . }}
{{ $cn := printf "%s.%s.svc" $svcName .Release.Namespace }}
{{ $cert := genSignedCert $cn nil (list $cn "") 365 $ca }}
{{ $existingSecret := (lookup "v1" "Secret" .Release.Namespace (include "vault-secrets-webhook.fullname" .)).data }}
{{ $caCert := get $existingSecret "ca.crt" | default ($ca.Cert | b64enc) }}

apiVersion: v1
kind: List
metadata:
items:

- apiVersion: v1
  kind: Secret
  metadata:
    name: {{ include "vault-secrets-webhook.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
  data:
    tls.crt: {{ get $existingSecret "tls.crt" | default ($cert.Cert | b64enc) }}
    tls.key: {{ get $existingSecret "tls.key" | default ($cert.Key | b64enc) }}
    ca.crt: {{ $caCert }}

- apiVersion: admissionregistration.k8s.io/v1
  kind: MutatingWebhookConfiguration
  metadata:
    name: {{ template "vault-secrets-webhook.fullname" . }}
  webhooks:
  - name: pods.{{ template "vault-secrets-webhook.name" . }}.admission
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ template "vault-secrets-webhook.fullname" . }}
        path: /pods
      caBundle: {{ $caCert }}
    rules:
    - operations:
      - CREATE
      apiGroups:
      - "*"
      apiVersions:
      - "*"
      resources:
      - pods
    failurePolicy: Ignore
    namespaceSelector:
      matchExpressions:
      - key: name
        operator: NotIn
        values:
        - {{ .Release.Namespace }}
    objectSelector:
      matchExpressions:
      - key: release
        operator: NotIn
        values: 
        - {{ .Release.Name }}
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None #Unknown
