{{ $ca := genCA "webhook-ca" 3650 }}
{{ $svcName := include "vault-secrets-webhook.fullname" . }}
{{ $cn := printf "%s.%s.svc" $svcName .Release.Namespace }}
{{ $cert := genSignedCert $cn nil (list $cn "") 365 $ca }}

apiVersion: v1
kind: List
metadata:
items:

- apiVersion: v1
  kind: Secret
  metadata:
    name: {{ template "vault-secrets-webhook.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
  data:
    tls.crt: {{ b64enc $cert.Cert }}
    tls.key: {{ b64enc $cert.Key }}
    ca.crt: {{ b64enc $ca.Cert }}

- apiVersion: admissionregistration.k8s.io/v1
  kind: MutatingWebhookConfiguration
  metadata:
    name: {{ template "vault-secrets-webhook.fullname" . }}
  webhooks:
  - name: pods.{{ template "vault-secrets-webhook.name" . }}.admission
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ template "vault-secrets-webhook.fullname" . }}
        path: /pods
      caBundle: {{ b64enc $ca.Cert }}
    rules:
    - operations:
      - CREATE
      apiGroups:
      - "*"
      apiVersions:
      - "*"
      resources:
      - pods
    failurePolicy: {{.Values.webhookFailurePolicy}}
    namespaceSelector:
      matchExpressions:
      - key: name
        operator: NotIn
        values:
        - {{ .Release.Namespace }}
    objectSelector:
      matchExpressions:
      - key: release
        operator: NotIn
        values: 
        - {{ .Release.Name }}
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None #Unknown
