apiVersion: apps/v1
kind: {{ .Values.kind }}
metadata:
  name: {{ template "vault-secrets-webhook.fullname" . }}
  labels:
    app: {{ template "vault-secrets-webhook.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: mutating-webhook
    {{- if .Values.deployment.labels }}
      {{- toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
spec:
  {{- if and (not .Values.HPA.enabled) (eq .Values.kind "Deployment")}}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "vault-secrets-webhook.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "vault-secrets-webhook.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/apiservice-webhook.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ template "vault-secrets-webhook.serviceAccountName" . }}
      {{- if .Values.deployment.securityContext }}
      securityContext:
        {{- toYaml .Values.deployment.securityContext | nindent 12 }}
      {{- end }}
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ template "vault-secrets-webhook.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
          - name: TLS_CERT_FILE
            value: /var/serving-cert/servingCert
          - name: TLS_PRIVATE_KEY_FILE
            value: /var/serving-cert/servingKey
          - name: INTERNAL_PORT
            value: "{{ .Values.service.internalPort }}"
          - name: DEBUG
            value: {{ .Values.debug | quote }}
{{- if .Values.gatewayCert.tlsCertsSecretName }}
          - name: AKEYLESS_GW_CERTIFICATE
            valueFrom:
              secretKeyRef:
                name: {{.Values.gatewayCert.tlsCertsSecretName | quote  }}
                key: tls.crt
{{- end }}
          - name: AKEYLESS_AGENT_IMAGE
            value: "{{ .Values.image.agentImage }}:{{ .Values.image.tag | default .Chart.AppVersion  }}"
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          volumeMounts:
          - mountPath: /var/serving-cert
            name: serving-cert
{{- if not .Values.openshiftEnabled }}
          securityContext: #//only for k8s - not openshift compatible
            runAsUser: 65534
            allowPrivilegeEscalation: false
{{- if .Values.containerSecurityContext }}
{{- toYaml .Values.containerSecurityContext | nindent 12 }}
{{- end }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
  {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
  {{- end }}
  {{- if .Values.affinity }}
      affinity:
{{ tpl .Values.affinity . | indent 8 }}
  {{- end }}
