{{- if or (.Values.serviceAccount.create) (.Values.restartRollout.enabled) }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ template "vault-secrets-webhook.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "vault-secrets-webhook.labels" . | nindent 4 }}
    {{- if .Values.serviceAccount.labels }}
      {{- toYaml .Values.serviceAccount.labels | nindent 4 }}
    {{- end }}
{{- end }}
