apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault-secrets-webhook.fullname" . }}
  labels:
    {{- include "vault-secrets-webhook.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
      {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: akls-metrics
  {{- end }}
  selector:
    {{- include "vault-secrets-webhook.selectorLabels" . | nindent 4 }}