apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault-secrets-webhook.fullname" . }}
  labels:
    app: {{ template "vault-secrets-webhook.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: mutating-webhook
    {{- if .Values.service.labels }}
      {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: akls-metrics
  {{- end }}
  selector:
    app: {{ template "vault-secrets-webhook.name" . }}
    release: {{ .Release.Name }}
