{{- if and .Values.metrics.enabled .Values.metrics.prometheus.enabled .Values.metrics.prometheus.podMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "vault-secrets-webhook.fullname" . }}-scrape-pods
  labels:
    release: prometheus  
spec:
  selector:
    matchLabels: {}
  podMetricsEndpoints:
  - port: akls-metrics
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: "true"
{{- end }}
