{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "vault-secrets-webhook.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-secrets-webhook.labels" . | nindent 4 }}
    {{- with .Values.pdb.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.pdb.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- else }}
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vault-secrets-webhook.selectorLabels" . | nindent 6 }}
{{- end }}
