{{- if .Values.restartRollout.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: akyeless-injector-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "patch", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "patch", "watch", "create", "delete", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["patch", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: akeyless-injector-role-binding
subjects:
- kind: ServiceAccount
  name: {{ template "vault-secrets-webhook.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: akyeless-injector-role
  apiGroup: rbac.authorization.k8s.io

{{end}}