{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ template "vault-secrets-webhook.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ template "vault-secrets-webhook.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: mutating-webhook
    {{- if .Values.serviceAccount.labels }}
      {{- toYaml .Values.serviceAccount.labels | nindent 4 }}
    {{- end }}
{{- end }}
