# Default values for akeyless-ssh-bastion.

replicaCount: 1

## Statefulsets rolling update update strategy
## Ref: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#rolling-update
##
updateStrategy: RollingUpdate

image:
  repository: akeyless/ssh-proxy
  pullPolicy: Always
  tag: latest
  dockerRepositoryCreds:

containerName: "ssh-bastion"

service:
  # Remove the {} and add any needed annotations regarding your LoadBalancer implementation
  annotations: {}
  type: LoadBalancer
  port: 22
  curlProxyPort: 9900

livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 60
  failureThreshold: 10

readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5

# Akeyless requires data persistence to be shared within all pods in the cluster
# Currently only ReadWriteMany is supported
# accessMode: ReadWriteMany
# Change the below values according to your environment except for the hostPath values
persistence:
  volumes: {}
#  volumes:
#    - name: akeyless-data
#        storageClassName: efs-ssh-bastion-sc
#        storageClassDriver: efs.csi.aws.com
#        size: 2Gi
#        mountPath: /var/run/requests
#        annotations:
#          volume.beta.kubernetes.io/storage-class: ""
#        matchLabels:
#          usage: "ssh-bastion-pv"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

HPA:
  # Set the below to false in case you do not want to add Horizontal Pod AutoScaling to the StatefulSet (not recommended)
  enabled: true
  minReplicas: 1
  maxReplicas: 14
  cpuAvgUtil: 50
  memAvgUtil: 50

config:
  CAPublicKey:
#  CAPublicKey: |
#    ssh-rsa AAAAAAA......


  # a full URL of Akeyless API Gateway
  apiGatewayURL: https://rest.akeyless.io

  # Relevant for Zero-Trust Access for non-SSH targets (e.g. DBs, K8s, AWS CLIs).
  # If provided, it's recommended to grant minimal permissions ("List" only) to the Zero-Trust Dynamic Secrets,
  # while the privilegedAccess will have "Read" and "List" permissions.
  privilegedAccess:
    accessID: ""
    accessKey: ""

  sessionTermination:
    enabled: false
    apiURL: ""
    apiToken: ""

  ## SSH log forwarding enables forwarding of the recordings of SSH sessions to customer log repository.
  ## Ref: https://docs.akeyless.io/docs/ssh-log-forwarding
  ##
  logForwarding:
    enabled: false
    settings: |
