apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-secret
spec:
  backendType: akeyless
  data:
    - key: my-app
      name: creds

---

apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-dynamic-secret
spec:
  backendType: akeyless
  data:
    - key: aws
      name: creds