{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "akeyless-zero-trust-bastion.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "akeyless-zero-trust-bastion.labels" . | nindent 4 }}
  annotations:
{{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
{{- end }}
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
{{- if .Values.ingress.hostname }}
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
         serviceName: {{ include "akeyless-zero-trust-bastion.fullname" . }}-svc
         servicePort: api
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.hostname }}
      secretName: {{ template "akeyless-zero-trust-bastion.ingressSecretTLSName" . }}
{{- end }}
{{- end }}