apiVersion: v1
kind: Secret
metadata:
  name: akeyless-docker-hub-bastion
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": pre-install
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ required "A valid .Values.conf.dockerRepositoryCreds entry required!" .Values.image.dockerRepositoryCreds }}
type: kubernetes.io/dockerconfigjson
---
{{ if not .Values.config.rdpRecord.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "akeyless-zero-trust-bastion.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "akeyless-zero-trust-bastion.name" . }}
    chart: {{ template "akeyless-zero-trust-bastion.chart" . }}
    release: "{{ .Release.Name }}"
type: Opaque
data:
  aws-access-key-id: {{ .Values.config.rdpRecord.s3.awsAccessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ .Values.config.rdpRecord.s3.awsSecretAccessKey | b64enc | quote }}
{{ end }}