{{ if not .Values.config.rdpRecord.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ template "akeyless-zero-trust-bastion.fullname" . }}
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ template "akeyless-zero-trust-bastion.name" . }}
        chart: {{ template "akeyless-zero-trust-bastion.chart" . }}
        release: "{{ .Release.Name }}"
type: Opaque
data:
    aws-access-key-id: {{ .Values.config.rdpRecord.s3.awsAccessKeyId | b64enc | quote }}
    aws-secret-access-key: {{ .Values.config.rdpRecord.s3.awsSecretAccessKey | b64enc | quote }}
{{ end }}