---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "akeyless-zero-trust-bastion.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "akeyless-zero-trust-bastion.labels" . | nindent 4 }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.enabled }}
  type: NodePort
  {{- else }}
  type: {{ required "A valid .Values.service.type entry required!" .Values.service.type }}
  {{- end }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
  selector:
    app: zero-trust-bastion