# This values.yaml file contains the default values for akeyless-secure-remote-access helm chart.
# The chart bundles both akeyless-zero-trust-bastion and akeyless-ssh-bastion. 
# Enter your configuration in the global and dedicated service sections

############
## Global ##
############

dockerRepositoryCreds:

# a full URL of Akeyless API Gateway
apiGatewayURL: https://rest.akeyless.io

# Secure remote access cluster name. Use a name that will help you understand
# the purpose of this cluster, for example, "sra-staging" or "us-west-prod"
clusterName: defaultCluster

# Relevant for Zero-Trust Access for non-SSH targets (e.g. DBs, K8s, AWS CLIs).
# If provided, it's recommended to grant minimal permissions ("List" only) to the Zero-Trust Dynamic Secrets,
# while the privilegedAccess will have "Read" and "List" permissions.
# optional credentials for zero-trust access: if provided, it is possible for
# end users to only have "list" permissions on Akeyless items if privileged
# credentials have "read" access.
privilegedAccess:
  # supported auth methods: AWS IAM, Azure AD, GCP and API Key;
  # for AWS IAM or Azure AD, or GCP provide only accessID;
  # for API Key, provide both accessID and accessKey
  accessID: ""
  accessKey: ""
   # limit access to privileged items only for these end user access ids.
   # if left empty, all access ids are allowed
  allowedAccessIDs: []
   # - p-1234
   # - p-5678
      
  # Azure Object ID to use with privileged credentials of type Azure AD
  azureObjectID: ""
  # Audience to use with privileged credentials of type GCP
  gcpAudience: "akeyless.io"

# Linux system HTTP Proxy
httpProxySettings:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""

####################################################
## Default values for akeyless-zero-trust-bastion ##
####################################################

ztbConfig:
  # Enable akeyless-zero-trust-bastion. Valid values: true/false.
  enabled: true
  replicaCount: 1

  image:
    repository: akeyless/zero-trust-bastion
    pullPolicy: Always
    # tag: latest
    
  containerName: "zero-trust-bastion"
  
  service:
    # Remove the {} and add any needed annotations regarding your LoadBalancer implementation
    annotations: {}
    type: LoadBalancer
    port: 8888

  ## Configure the ingress resource that allows you to access the
  ## akeyless-zero-trust-bastion installation. Set up the URL
  ## ref: http://kubernetes.io/docs/user-guide/ingress/
  ##
  ingress:
    ## From nginx ingress-controller version xxxx the annotation is no longer supported use ingressClass instead
    # ingressClass: nginx
    ## Set to true to enable ingress record generation
    ##
    # enabled: true
    annotations: {}
  # Example for Nginx ingress
    #  annotations:
      #  kubernetes.io/ingress.class: nginx
      #  nginx.ingress.kubernetes.io/ssl-redirect: "true"
      #  nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
      #  nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      #  nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      #  nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
      #  nginx.ingress.kubernetes.io/proxy-buffers-number: "4"

  # IMPORTANT: When using DB application such as mysql, mssql, and mongodb, the ingress must be configured with "sticky" session!
  # Example for sticky session on Nginx ingress
  #      nginx.ingress.kubernetes.io/affinity: "cookie"
  #      nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
  #      nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"

    hostname: zero-trust-bastion.local
    ## Path for the default host
    ##
    path: /

    ## Enable TLS configuration for the hostname defined at ingress.hostname parameter
    ## TLS certificates will be retrieved from a TLS secret with name: {{- printf "%s-tls" .Values.ingress.hostname }}
    ## or a custom one if you use the tls.existingSecret parameter
    ##
    tls: false

    ## Set this to true in order to add the corresponding annotations for cert-manager
    ##
    certManager: false

    ## existingSecret: name-of-existing-secret

  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 30
    failureThreshold: 10

  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 5

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  HPA:
    # Set the below to false in case you do not want to add Horizontal Pod AutoScaling to the Deployment
    enabled: true
    minReplicas: 1
    maxReplicas: 14
    cpuAvgUtil: 50
    memAvgUtil: 50
  
  config:
    rdpRecord:
      enabled: false
      # automatically upload session recordings to S3 in your AWS account
      s3:
        region: ""
        bucketName: ""
        bucketPrefix: ""
        # optional, run with explicit credentials (without AWS IAM roles)
        awsAccessKeyId: ""
        awsSecretAccessKey: ""

      # Specifies an existing secret to be used for bastion, management AWS credentials
      existingSecret: ""

#############################################
## Default values for akeyless-ssh-bastion ##
#############################################

sshConfig:
# Enable akeyless-ssh-bastion. Valid values: true/false.
  enabled: true

  ## Statefulsets rolling update update strategy
  ## Ref: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#rolling-update
  updateStrategy: RollingUpdate


  service_account:
    enabled: false
    use_existing: false
    serviceAccountName: akeyless
    ## For google workload identity have a look in the following link for the use of nodeSelector.
    ## ref: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
    nodeSelector:
#      iam.gke.io/gke-metadata-server-enabled: "true"
    annotations:
#      - iam.gke.io/gcp-service-account: change_me_to_gcp_service_account
#      - eks.amazonaws.com/role-arn: arn:aws:iam::40XXXXXXXX75:role/eksctl-Role1-XXXXXXXX


  image:
    repository: akeyless/ssh-proxy
    pullPolicy: Always
    # tag: latest

  containerName: "ssh-bastion"

  service:
    # Remove the {} and add any needed annotations regarding your LoadBalancer implementation
    annotations: {}
    type: LoadBalancer
    port: 22
    curlProxyPort: 9900

  # Akeyless requires data persistence to be shared within all pods in the cluster
  # Currently only ReadWriteMany is supported
  # accessMode: ReadWriteMany
  # Change the below values according to your environment except for the hostPath values
  persistence:
    volumes: {}
  #  volumes:
    #  - name: akeyless-data
    #    storageClassName: efs-ssh-bastion-sc
    #   #  storageClassDriver: efs.csi.aws.com
    #    size: 100Mi
    #    annotations:
    #     volume.beta.kubernetes.io/storage-class: ""
    #    matchLabels:
    #     usage: "ssh-bastion-pv"

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  HPA:
    # Set the below to true only when using a shared persistent storage (defined at .persistence.volumes) 
    enabled: false
    minReplicas: 1
    maxReplicas: 14
    cpuAvgUtil: 50
    memAvgUtil: 50

  config:
    CAPublicKey:
    # CAPublicKey: |
      
    sessionTermination:
    ## Session Termination is available for okta and keycloak
    ## Ref: https://docs.akeyless.io/docs/professional-bastion
      enabled: false
      apiURL: ""
      apiToken: ""

    ## SSH log forwarding enables forwarding of the recordings of SSH sessions to customer log repository.
    ## Ref: https://docs.akeyless.io/docs/ssh-log-forwarding
    ##
    logForwarding:
      enabled: false
      # Syslog example
      # settings: |
        # target_syslog_tag="ssh-audit-export"
        # target_log_type="syslog"
        # target_syslog_network="udp"
        # target_syslog_host="<host>:<port>"
