{{- $ga := .Values.gatewayAPI | default dict -}}
{{- if and $ga.enabled $ga.tlsRoutes -}}
{{- $default := include "gatewayApi.backendService" . -}}
{{- range $i, $r := $ga.tlsRoutes }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ include "gatewayApi.gatewayName" $ }}-tls-{{ $i }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "gatewayApi.labels" $ | nindent 4 }}
spec:
  parentRefs:
  {{- if $ga.parentRefs }}
    {{- include "gatewayApi.parentRefs" $ | nindent 4 }}
  {{- else }}
    - name: {{ include "gatewayApi.gatewayName" $ }}
      sectionName: tls
  {{- end }}
  {{- with $r.hostname }}
  hostnames:
    - {{ . | quote }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ $r.serviceName | default $default }}
          port: {{ include "gatewayApi.portNumber" (dict "port" $r.servicePort "root" $) }}
{{- end }}
{{- end -}}
