name: Api-gw Latest App Version Release

on:
  deployment:

jobs:
  update-latest-api-gw-version:
    if: github.event.deployment.task == 'update-latest-api-gw-version'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Update latest api-gw version
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.deployment) }}
        run: .github/scripts/apigw_latest_version_release.sh