name: Release Charts

on:
  deployment:
  push:
    branches:
      - main
      
concurrency:
  group: Release Charts

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      # See https://github.com/helm/chart-releaser-action/issues/6
      - name: Install Helm
        run: |
          curl -fsSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name: Add dependency chart repos
        run: |
          helm repo add stable https://charts.helm.sh/stable
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.TOKEN_GITHUB }}"

  Slack-Notification-on-failure:
    name: Slack-On-Failure-Notification
    runs-on: ubuntu-20.04
    needs: [ release ]
    if: (failure() && needs.*.result != 'success')
    steps:
      - name: Prepare Slack Message On Failure
        id: slack-message-failure-creator
        run: |
          SLACK_MESSAGE="
          *Status:* Failure
          :terminator:"
          delimiter="$(openssl rand -hex 8)"
          echo "slack-message<<${delimiter}" >> $GITHUB_ENV
          echo "${SLACK_MESSAGE//$/%0A}" >> $GITHUB_ENV
          echo "${delimiter}" >> $GITHUB_ENV

      - name: Slack Failure Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: 'operations'
          SLACK_COLOR: '#bd3232'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: Helm Chart Release Failed!
          SLACK_MESSAGE: '${{ env.slack-message }}'
          SLACK_USERNAME: githubBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_OPERATIONS_WEBHOOK }}
          SLACK_FOOTER: Akeyless.io Helm Chart Release