name: Update Manifests

on:
  deployment:
  workflow_dispatch:

jobs:
  update_manifests:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      # The below permission gives the workflow permission to commit directly to the repo
      contents: write
    name: Update All Generated Manifests
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout Manifests Repo
      uses: actions/checkout@v3
      with:
        repository: akeylesslabs/akeyless-k8s-manifests
        token: ${{ secrets.AKEYLESS_CI_COMMIT_PUSH_TOKEN }}
        path: manifest_work_dir

      # The below step will pull in generated manifests from the last helm chart release and store them within the repo
    - name: Process Manifests (akeyless-secrets-injection)
      run: |
        .github/scripts/generate_manifests.sh


    - name: After Checker
      run: tree -p ${GITHUB_WORKSPACE}/manifests
