name: Update Manifests

on:
  workflow_dispatch:

jobs:
  update_manifests:
    runs-on: ubuntu-20.04
    name: Update All Generated Manifests
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.AKEYLESS_CI_COMMIT_PUSH_TOKEN }}

    - name: Checkout Manifests Repo
      uses: actions/checkout@v3
      with:
        repository: akeylesslabs/akeyless-k8s-manifests
        token: ${{ secrets.AKEYLESS_CI_COMMIT_PUSH_TOKEN }}
        path: manifest_work_dir

      # The below step will pull in generated manifests from the last helm chart release and store them within the repo
    - name: Process Manifests (akeyless-secrets-injection)
      run: |
        .github/scripts/generate_manifests.sh

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.AKEYLESS_CI_COMMIT_PUSH_TOKEN }}
        branch: ${{ env.branch_name }}
        commit-message: generated new manifest
        title: 'Auto Generate new manifest'
        body: >
          This PR is auto-generated for
          Generated New Manifest
        labels: Generate Manifest ,Auto PR

    - name: Checkout akeyless-environments code after PR
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.AKEYLESS_CI_COMMIT_PUSH_TOKEN }}

    - name: Run commands for merge & push & delete branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "$GITHUB_ACTOR"
        git pull
        git merge origin/${{ env.branch_name }}
        git push -u
        git push --delete origin ${{ env.branch_name }}

    - name: After Checker
      run: tree -p ${GITHUB_WORKSPACE}/manifests

